version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
    - 80:80
    networks:
      - gis_4ban_network
    volumes:
      - /home/success899/nginx.conf:/etc/nginx/nginx.conf
      - gis_4ban_static:/data/static/
      - gis_4ban_media:/data/media/

  django:
    image: test_django:4
    networks:
      - gis_4ban_network
    volumes:
      - gis_4ban_static:/home/test/staticfiles/
      - gis_4ban_media:/home/test/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_4ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: a123123b
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: a123123b


networks:
  gis_4ban_network:

volumes:
  gis_4ban_static:
  gis_4ban_media:
  gis_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true